"""empty message

Revision ID: 322d3000e8c2
Revises: a144ca0a1e76
Create Date: 2021-04-25 22:18:04.702769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322d3000e8c2'
down_revision = 'a144ca0a1e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.LargeBinary(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
