"""empty message

Revision ID: c07203b29104
Revises: a7954c8be3ca
Create Date: 2021-07-04 13:46:40.789916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c07203b29104'
down_revision = 'a7954c8be3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session_status = postgresql.ENUM('PENDING', 'ANSWERED', 'MISSED', name='status_session_enum')
    session_status.create(op.get_bind())

    op.add_column('sessions', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('status', sa.Enum('PENDING', 'ANSWERED', 'MISSED', name='status_session_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session_status = postgresql.ENUM('PENDING', 'ANSWERED', 'MISSED', name='status_session_enum')
    session_status.drop(op.get_bind())

    op.drop_column('sessions', 'comments')
    op.drop_column('sessions', 'status')
    # ### end Alembic commands ###
