name: deploy
on: push

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add api remote origin
        run: |
          git remote add heroku-api https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_SERVE_APP_NAME }}.git
      - name: Deploy api to Heroku
        run: |
          git subtree push --prefix server heroku-api master
          - name: Deploy to Heroku
            uses: akhileshns/heroku-deploy@v3.12.12
            with:
              heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
              heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
              heroku_email: ${{ secrets.HEROKU_EMAIL }}
